### ISSUE TITLE
Dedup process needs more time

### ISSUE THREAD

**Issue by ggabernet** [nf-core/bcellmagic#14]

**Comment by apeltzer** [comment]
I got some train time to increase it now ;)

**Comment by ggabernet** [comment]
Awesome, thanks!

**Comment by apeltzer** [comment]
Addressed in PR #15

**Comment by ggabernet** [comment]
Could you add even more time? 30 h I would suggest.

More samples (5) now run through the dedup step but 3 are still failing because of not enough runtime.

**Comment by ggabernet** [comment]
Addressed in PR #16
